name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 5.16/stable

      - name: Install rockcraft
        run: |
          sudo snap install --classic --channel edge rockcraft
      - name: Build ROCK
        run: rockcraft pack --verbose

      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: lego-rock
          path: "lego_*.rock"
