name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 2'

concurrency:
    group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
    cancel-in-progress: true

jobs:

  build:
    uses: canonical/identity-credentials-workflows/.github/workflows/build-rock.yaml@v0

  scan:
    needs: build
    uses: canonical/identity-credentials-workflows/.github/workflows/scan-rock.yaml@v0

  publish:
    if: github.ref_name == 'main'
    needs: [scan, build]
    uses: canonical/identity-credentials-workflows/.github/workflows/publish-rock.yaml@v0
